server:
  port: 8080
spring:
  data:
    mongodb:
      #host: 127.0.0.1
      #host: mongo  # Altere para o nome do serviço no Docker
      port: 27017
      authentication-database: admin
      #usermane: root
      #username: root
      password: example
      database: gamechangedb

logging:
  level:
    org.springframework.security: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET:mysecretkey}  # Segredo do JWT, com valor padrão "mysecretkey"

aws:
  region: us-east-1
#  credentials:
#    access-key: ${AWS_ACCESS_KEY_ID}
#    secret-key: ${AWS_SECRET_ACCESS_KEY}
  bucket:
    name: bucket-1  # ${AWS_BUCKET_NAME} # Defina isso como variável de ambiente